services:
  express-app:
    image: elliotathelsinki/express-app:latest
    ports:
      - 80:8080

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
